#!/bin/sh

# Copyright Gentoo Technologies, Inc and Pieter Van den Abeele <pvdabeel@gentoo.org> 2003
# Distributed under the GPL v2

BOOT_unmount() {
	umount ${_ISO_} 2>/dev/null
}

BOOT_clean() {
	BOOT_unmount
	rm -rf ${_ISO_}
}

BOOT_prepare() {

	mkdir -p ${_ISO_}

	cp -rf ${_FILES_}/boot ${_ISO_}
	cp -rf ${_FILES_}/docs ${_ISO_}

	mkdir -p ${_ISO_}/${_ARCH_}-stages
    
	cp -rf ${_STAGES_}/*${_ARCH_}* ${_ISO_}/${_ARCH_}-stages/
    
	mv ${_ROOT_}/live.gcloop ${_ISO_}/
}

BOOT_finalize() {
	cp ${_LOOP_}/boot/vmlinux          ${_ISO_}/boot/
	cp ${_LOOP_}/boot/System.map       ${_ISO_}/boot/
	cp ${_LOOP_}/usr/lib/yaboot/yaboot ${_ISO_}/boot/
}

BOOT_create() {
	cd ${_ISO_}
	mkisofs -J -r -netatalk -hfs -probe -map boot/map.hfs \
		-part -no-desktop -hfs-volid GentooPPC_${_VERSION_} \
		-hfs-bless ./boot -o ${_ROOT_}/${_ISONAME_} .
	cd ${_ROOT_}
}

BOOT_burn() {
	cdrecord -v -data dev=ATAPI:0,0 ${1}
}
