#!/bin/sh

# Copyright Gentoo Technologies, Inc and Pieter Van den Abeele <pvdabeel@gentoo.org> 2003
# Distributed under the GPL v2

function GCLOOP_build() {
    cd ${_ROOT_}
    if [ ! -e ${_GCLOOP_DIR_} ]
    then
    	tar jxvf ${_GCLOOP_}
    	cd ${_GCLOOP_DIR_}
    	make KERNEL_DIR=${_LOOP_}/usr/src/linux 
    	cd ${_ROOT_}
    fi
}

function GCLOOP_install() {
    mkdir -p ${_LOOP_}/lib/modules/misc
    cp ${_GCLOOP_DIR_}/cloop.o ${_LOOP_}/lib/modules/misc/ 
}

function GCLOOP_clean() {
    rm -rf ${_GCLOOP_DIR_}
}
