#!/bin/sh

# Copyright Gentoo Technologies, Inc and Pieter Van den Abeele <pvdabeel@gentoo.org> 2003
# Distributed under the GPL v2

if [ "${TERM}" != "vt100" ] ; then
	_RD_="\x1b[31;01m"
	_GR_="\x1b[32;01m"
	_GY_="\x1b[32;02m"
	_YL_="\x1b[33;01m"
	_CY_="\x1b[36;01m"
	_BL_="\x1b[34;01m"
	_NC_="\x1b[0;0m"
fi

function err()
{
	echo -e " * ${_RD_}ERROR${_NC_}: ${1} "
}

function wrn()
{
	echo -e " * ${_YL_}WARNING${_NC_}: ${1} "
}

function msg()
{
	echo -e ">>> ${1} "
}

function dbg()
{
	echo -e " * ${_BL_}DEBUG${_NC_}: ${1} "
}

function waiting()
{
	echo 
	echo ">>> Waiting 5 seconds before starting..."
	echo ">>> (Control-C to abort)..."
	echo -n -e ">>> Starting in: "
	echo -n -e "${_RD_}5${_NC_} "
	sleep 1 ; echo -n -e "${_RD_}4${_NC_} "
	sleep 1 ; echo -n -e "${_RD_}3${_NC_} "
	sleep 1 ; echo -n -e "${_RD_}2${_NC_} "
	sleep 1 ; echo -n -e "${_RD_}1${_NC_} "
	sleep 1 ; echo ; echo
}

function zapmost() {
	local rnd
	local dir
        local loc
	
	rnd=`date +%S`
	loc=`pwd`
	dir=${1}
	
	[ ! -e  "${dir}/" ] && echo "zapmost: ${dir}/ not found; skipping..." && return 1
	shift
	
	cd ${dir}
	tar cvf ../${rnd}zap.tar ${*}  >/dev/null 2>/dev/null || true
	rm -rf  *                      >/dev/null 2>/dev/null || true
	tar xvf ../${rnd}zap.tar       >/dev/null 2>/dev/null || true
	rm -rf  ../${rnd}zap.tar       >/dev/null 2>/dev/null || true
	cd ${loc}
	return 0
}
