#!/bin/sh

# Copyright Gentoo Technologies, Inc and Pieter Van den Abeele <pvdabeel@gentoo.org> 2003
# Distributed under the GPL v2

## TODO: use mkinitrd for selinux support

function INITRD_unmount() {
	umount ${_INITRD_} 2>/dev/null
}

function INITRD_clean() {
	INITRD_unmount
	rm -rf ${_INITRD_} 
	rm -rf ${_BUSYBOX_DIR_}
}

function INITRD_prepare() {
	cd ${_ROOT_}
	if [ ! -e ${_BUSYBOX_DIR_} ]
	then
		tar jxvf ${_BUSYBOX_}
		cd ${_BUSYBOX_DIR_}
		cp ${1} .config
		make clean && make || err "Building busybox failed"
		cd ${_ROOT_}
	fi
}

function INITRD_create() {

	install -d ${_INITRD_}
	dd if=/dev/zero of=${_ISO_}/boot/initrd.img bs=1k count=${_INITRD_SIZE_}
	mke2fs -F -q -N${_INITRD_SIZE_} ${_ISO_}/boot/initrd.img
	mount -t ext2 -o loop ${_ISO_}/boot/initrd.img ${_INITRD_}
	if [ ! -e ${_INITRD_}/bin ]
	then
		install -d ${_INITRD_}/{bin,etc,usr,proc,tmp}	
		ln -s bin ${_INITRD_}/sbin
		ln -s ../bin ${_INITRD_}/usr/bin
		ln -s ../bin ${_INITRD_}/usr/sbin
		(mkdir ${_INITRD_}/dev;cd ${_INITRD_}/dev;MAKEDEV generic-powerpc)
	fi
	cp -rf ${_FILES_}/initrd/*    ${_INITRD_}/
	cp ${_BUSYBOX_DIR_}/busybox   ${_INITRD_}/bin

	for i in '[' ash basename cat chroot clear cp dirname echo env false find \
	        grep gunzip gzip insmod ifconfig ln ls loadkmap losetup lsmod mkdir mknod modprobe more mount mv \
	        pivot_root ps pwd rm rmdir rmmod sh sleep tar test touch true umount uname \
	        xargs yes zcat chmod chown; do 
		
		rm -f ${_INITRD_}/bin/$i
		ln ${_INITRD_}/bin/busybox ${_INITRD_}/bin/$i 
	
	done 

	mkdir -p ${_INITRD_}/mnt
	mkdir -p ${_INITRD_}/mnt/live

	mkdir -p ${_INITRD_}/lib
	mkdir -p ${_INITRD_}/lib/modules
	
	cp -rf ${_LOOP_}/lib/modules/* ${_INITRD_}/lib/modules/
	chmod +x ${_INITRD_}/linuxrc*
	umount ${_INITRD_}/ 2>/dev/null
	gzip -f -9 ${_ISO_}/boot/initrd.img
}
