#!/bin/sh

# Copyright Gentoo Technologies, Inc and Pieter Van den Abeele <pvdabeel@gentoo.org> 2003
# Distributed under the GPL v2

function LOOP_mount() {
	mount -o bind ${1} ${_LOOP_}/proc
	mkdir -p ${_LOOP_}/usr/portage
	mount -o bind ${2} ${_LOOP_}/usr/portage
}

function LOOP_unmount() {
	umount ${_LOOP_}/proc        2>/dev/null || true
	umount ${_LOOP_}/usr/portage 2>/dev/null || true
}

function LOOP_clean() {
	LOOP_unmount
	rm -rf ${_LOOP_}
}

function LOOP_ERROR() {
	err ${1}
	LOOP_unmount
	exit 1
}

function LOOP_create() {
	if [ ! -f ${1} ]; then
		err "Stage not found"
		exit 1
	fi

	if [ ! -d ${_LOOP_} ]; then 
		cd ${_ROOT_}
		mkdir -p ${_LOOP_}
    	cd ${_LOOP_}
		tar jxpf ${1} || (err "Unpacking stage failed" ; exit 1 )
		cd ${_ROOT_}
	else
		msg "Skipped unpacking stage - ${_LOOP_} exists"
	fi
}

function LOOP_setup {
	mkdir -p ${_LOOP_}/mnt/.init.d
	mkdir -p ${_LOOP_}/livecd/
	mkdir -p ${_LOOP_}/livecd/src/
	mkdir -p ${_LOOP_}/livecd/config/

	cp -rf ${1}/* ${_LOOP_}/etc/                # copy in complete etc directory
	cp -rf ${2}/* ${_LOOP_}/livecd/src/         # copy in livecd src directory stuff
	cp -rf ${3}/* ${_LOOP_}/livecd/config/      # copy in livecd config directory stuff
	cp -rf ${4}   ${_LOOP_}/etc/                # copy in system resolv.conf

    echo ${5} > ${_LOOP_}/etc/hostname
}

LOOP_finalize() {
    cp ${1} ${_LOOP_}/etc/
    dd if=/dev/zero of=${_ROOT_}/live.gcloop.tmp bs=1k count=${_LOOP_SIZE_}
    mke2fs -F -q ${_ROOT_}/live.gcloop.tmp
    mkdir -p ${_ROOT_}/gcloop
    mount -t ext2 -o loop ${_ROOT_}/live.gcloop.tmp ${_ROOT_}/gcloop
    cp -a ${_LOOP_}/* ${_ROOT_}/gcloop
    umount ${_ROOT_}/gcloop
    rm -rf ${_ROOT_}/gcloop
    ${_GCLOOP_DIR_}/create_compressed_fs ${_ROOT_}/live.gcloop.tmp 131072 > ${_ROOT_}/live.gcloop
    rm -rf ${_ROOT_}/live.gcloop.tmp  
}

