#!/bin/sh

# Copyright Gentoo Technologies, Inc and Pieter Van den Abeele <pvdabeel@gentoo.org> 2003
# Distributed under the GPL v2

### DEFAULT SETTINGS DO NOT CHANGE ###

_ROOT_=`pwd`

### BUILD DIRECTORIES ###

_ISO_=${_ROOT_}/iso
_LOOP_=${_ROOT_}/loop
_INITRD_=${_ROOT_}/initrd

### STUFF DIRECTORIES ### 

_GRP_=${_ROOT_}/grp
_DOCS_=${_ROOT_}/docs
_STAGES_=${_ROOT_}/stages

_FILES_=${_ROOT_}/files
_BUSYBOX_=${_FILES_}/busybox/busybox-1.00-pre3.tar.bz2
_BUSYBOX_DIR_=${_ROOT_}/busybox-1.00-pre3

_GCLOOP_=${_FILES_}/cloop/gcloop-0.66.3.tar.bz2
_GCLOOP_DIR_=${_ROOT_}/gcloop-0.66.3

### default config settings ###

_VERSION_="2004.0"
_ARCH_="ppc"
_STAGE_="${_STAGES_}/stage3-${_ARCH_}-${_VERSION_}.tbz2"
_TYPE_="stage3"
_ISONAME_="gentoo-${_ARCH_}-${_VERSION_}-`date +%d%m%y`.iso"
_KERNEL_="ppc-sources"
_KERNEL_CONFIG_="kernel.conf"
_HOSTNAME_="LiveCD.GentooPPC"
_UPDATE_="no"
_EMERGE_="beep"
_UNMERGE_="beep"

_DEVELOPER_="yes"
_INITRD_SIZE_=10000
_LOOP_SIZE_=410000
