#!/bin/sh

# Copyright Gentoo Technologies, Inc and Pieter Van den Abeele <pvdabeel@gentoo.org> 2003
# Distributed under the GPL v2

du -c -s bin boot etc home lib mnt opt root sbin usr/X11R6 usr/bin usr/doc usr/include usr/lib usr/info usr/libexec usr/local usr/man usr/powerpc-unknown-linux-gnu usr/sbin usr/share | grep total | awk '{ print ;}'

du -c -s bin boot etc home lib mnt opt root sbin usr var | grep total | awk '{ print ;}'
