#!/bin/bash
sudo su -

DATE=`wget -O - http://dev.gentoo.org/~agaffney/gli/ 2>/dev/null | grep -e 'installer-' | sed -e 's:^.\+>installer-::' -e 's:\.tar\.bz2.\+$::'`
wget http://dev.gentoo.org/~agaffney/gli/snapshots/installer-${DATE}.tar.bz2
tar -xjf installer-${DATE}.tar.bz2

cd installer/src/fe/dialog
./gli-dialog.py
