#!/bin/bash

xhost +
sudo su -

DATE=`wget -O - http://dev.gentoo.org/~agaffney/gli/ 2>/dev/null | grep -e 'installer-' | sed -e 's:^.\+>installer-::' -e 's:\.tar\.bz2.\+$::'`
wget http://dev.gentoo.org/~agaffney/gli/snapshots/installer-${DATE}.tar.bz2
tar -xjf installer-${DATE}.tar.bz2

export DISPLAY=:0.0
cd installer/src/fe/gtk
./gtkfe.py
