#!/bin/sh

# dependency_check ucl lzo cdrtools 

_START_=`date +%H:%M:%S`
_CONFIG_=${2}
_COMMAND_=${1}

source src/globals
source src/settings
source config/make.conf
source config/livecd.conf
source src/loop
source src/bootiso
source src/initrd
source src/gcloop

case "${_COMMAND_}" in
clean )
LOOP_clean
BOOT_clean
INITRD_clean
GCLOOP_clean
;;

mount )
LOOP_mount /proc /usr/portage
;;

unmount )
LOOP_unmount
BOOT_unmount
INITRD_unmount
;;

build )
msg "Starting ${_ISONAME_} build"

### LOOP STUFF ###

LOOP_create ${_STAGE_}
LOOP_setup  ${_FILES_}/loop/etc ${_ROOT_}/src ${_ROOT_}/config /etc/resolv.conf ${_HOSTNAME_}

LOOP_mount /proc /usr/portage

msg "Diving into live environment"

chroot ${_LOOP_} /livecd/src/inside/kernel
[ $? -ne 0 ] && err "Upgrading to stage3/kernel building failed" && LOOP_unmount && exit 1

GCLOOP_build

chroot ${_LOOP_} /livecd/src/inside/build
[ $? -ne 0 ] && err "Building extra stuff failed" && LOOP_unmount && exit 1

GCLOOP_install

chroot ${_LOOP_} /livecd/src/inside/clean 
[ $? -ne 0 ] && err "Cleaning failed" && LOOP_unmount && exit 1

LOOP_unmount
LOOP_finalize ${_FILES_}/loop/etc/issue ${_GCLOOP_DIR_}

### BOOT.ISO BEFORE ###

msg "Preparing boot.iso"
BOOT_prepare

### INITRD STUFF STUFF ### 

INITRD_prepare
INITRD_create

### BOOT.ISO AFTER ###

BOOT_finalize
BOOT_create

msg "Finished ${_ISONAME_} build"
echo
msg "SUMMARY:"
echo
msg "${_ISONAME_} build completed at `date +%H:%M:%S`"
msg "${_ISONAME_} build started at   ${_START_}"
;;


gcloop )
GCLOOP_build
GCLOOP_install
;;

initrd )
INITRD_prepare /root/ppclivecd/config/busybox.config
INITRD_create
;;

rebuild_loop )
LOOP_finalize ${_FILES_}/loop/etc/issue ${_GCLOOP_DIR_}
BOOT_prepare
;;

rebuild )
BOOT_finalize
BOOT_create
;;

burn )
BOOT_burn ${_ISONAME_}
;;

prepare )
BOOT_prepare
;;

* )
cat src/usage
;;
esac
