#!/bin/sh

if [ ! ${USER}=="root" ]; then 
 echo "you have to run this script as root :-)"
 exit 1
fi

XSESSION=`dialog --stdout --radiolist "Please choose a Window Manager:" 10 60 3 Gnome "GNOME desktop environment" off kde-3.2.0 "KDE desktop environment" off`
sed -e 's/XSESSION=.*/XSESSION='${XSESSION}'/g' /etc/rc.conf.template > /etc/rc.conf
Xautoconfig4
