#!/bin/bash
#This script is designed to tweak the system for CD-based opengl-update
#set up our flexible opengl stuff:

if [ ! -e ${CD_BUILDCHROOT}/etc/opengl ]
then
	cp ${LIVECD_ROOT}/profiles/global/opengl-update ${CD_BUILDCHROOT}/usr/sbin
	#move symlinks to a malleable /etc/opengl directory.
	install -d ${CD_BUILDCHROOT}/etc/opengl
	mv ${CD_BUILDCHROOT}/usr/lib/libGL.* ${CDROOT}/etc/opengl/
	mv ${CD_BUILDCHROOT}/usr/lib/libGLcore.* ${CDROOT}/etc/opengl/
	ln -sf /etc/opengl/libGL.so ${CD_BUILDCHROOT}/usr/lib/libGL.so
	ln -sf /etc/opengl/libGL.so.1 ${CD_BUILDCHROOT}/usr/lib/libGL.so.1
	ln -sf /etc/opengl/libGLcore.so ${CD_BUILDCHROOT}/usr/lib/libGLcore.so
	ln -sf /etc/opengl/libGLcore.so.1 ${CD_BUILDCHROOT}/usr/lib/libGLcore.so.1
	mv ${CD_BUILDCHROOT}/usr/X11R6/lib/libMesaGL.so ${CDROOT}/etc/opengl/
	ln -sf /etc/opengl/libMesaGL.so ${CD_BUILDCHROOT}/usr/X11R6/lib/libMesaGL.so
	mv ${CD_BUILDCHROOT}/usr/X11R6/lib/modules/extensions/libglx.so ${CDROOT}/etc/opengl/
	mv ${CD_BUILDCHROOT}/usr/X11R6/lib/modules/extensions/libglx.a ${CDROOT}/etc/opengl/
	ln -s /etc/opengl/libglx.so ${CD_BUILDCHROOT}/usr/X11R6/lib/modules/extensions/libglx.so
	ln -s /etc/opengl/libglx.a ${CD_BUILDCHROOT}/usr/X11R6/lib/modules/extensions/libglx.a
fi

