.TH "CREATE_GCLOOP" "6" "Jan 2004" "gcloop 0.99" "gcloop"
.SH NAME
create_gcloop \- creates gcloop images [PLACEHOLDER]
.SH SYNOPSIS
.B create_gcloop [options] infile blocksize > outfile
.B create_gcloop -V
.SH DESCRIPTION
\fBcreate_gcloop\fR can be utilized to create a compressed 
image to be used as compressed loopback.

.SH PARAMETERS
.TP
.BR infile
Input image file, to use stdin instead use "-" instead of a filename
.TP
.BR outfile
Output file
.TP
.BR blocksize
Blocksize in bytes. The number has to be a multiple of 512.The 
suggested sizes are 65536 (64k) and 131072 (128k). Due to kernel
memory allocation 128k is the current max
.TP
.SH OPTIONS
.TP
.BR -c
\&[not implemented yet] 
Set the compression level, the range is up to the compressor used
commonly 0-10 for ucl algorithm and 0-9 for zlib algorithm.
.TP
.BR -V
Print the version and exit.
.TP
.BR -C
\&[not implemented yet]
Set the compression algorithm
.TP
.SH "EXAMPLES"
.B create_gcloop
image.iso 65536 >image.ucl
.br
.B create_gcloop
-c 9 image.ucl 131072  > image.ucl
.br
mkisofs -r datadir |
.B create_gcloop
 - 131072 > image.ucl
.SH "REPORTING BUGS"
Please report bugs via http://bugs.gentoo.org/
.SH "SEE ALSO"
.BR compress_gcloop (1),
.BR extract_gcloop (1)
.SH AUTHORS
Paul 'Rusty' Russel (original author)
.br
Klaus Knopper <knopper@knopper.net>
.br
Valentijn Sessink <valentyn@openoffice.nl>  (total rewrite)
.br
Luca Barbato <lu_zero@gentoo.org> (revamped version)
