.TH "EXTRACT_GCLOOP" "1" "Jan 2004" "gcloop 0.99" "gcloop"
.SH NAME
extract_gcloop \- extracts gcloop images [PLACEHOLDER]
.SH SYNOPSIS
.B extract_gcloop infile  > outfile
.B extract_gcloop -V
.SH DESCRIPTION
\fBextract_gcloop\fR can be utilized to extract and verify a compressed 
image.

.SH PARAMETERS
.TP
.BR infile
Input compressed image file
.TP
.BR outfile
Output image file
.TP
.SH OPTIONS
.TP
.BR -V
Print the version and exit.
.TP
.SH "EXAMPLES"
.B extract_gcloop
image.ucl >image.iso
.br
.SH "REPORTING BUGS"
Please report bugs via http://bugs.gentoo.org/
.SH "SEE ALSO"
.BR compress_gcloop (1),
.BR create_gcloop (1)
.SH AUTHORS
Paul 'Rusty' Russel (original author)
.br
Klaus Knopper <knopper@knopper.net>
.br
Luca Barbato <lu_zero@gentoo.org> (revamped version)
