#!/bin/bash
################################################
# quick script to roll a new genpatches release.
################################################

dir="${@}"
[ -z "${dir}" ] && dir="$(find ./ -type d -and -not -iname "*CVS*" | tail -n 1)"

file="${dir/\.\//}.tar.bz2"
tar -cvjf ${file} ${dir} --exclude=CVS
md5="$(md5sum ${file})"

echo
echo Roll complete.
echo Produced: ${file} [md5: ${md5/\ */}]
file ${dir/\.\//}.tar.bz2
echo
