#!/bin/bash
################################################
# quick script to roll a new genpatches release.
################################################

dir="${@}"
[ -z "${dir}" ] && dir="$(find ./ -type d -and -not -iname "*CVS*" | tail -n 1)"
tar -cvjf ${dir/\.\//}.tar.bz2 ${dir} --exclude=CVS

echo Roll complete.
echo produced: ${dir/\.\//}.tar.bz2
file ${dir/\.\//}.tar.bz2
