#!/bin/bash
if [ "$#$1" != "1LaunchInGen" ]; then
	echo "You really don't want to run this..."; exit; fi
# partitioning
# Setup functions for script
calc_ideal_swap () {
	# Find out how much RAM they got and make enough swap to total 256 MB
	sysram="`grep 'MemTotal:' /proc/meminfo | { read a b c; echo $b; }`"
	idealram="268435456"
	let idealswap=$idealram-$sysram
	if [ $idealswap -le 33554432 ]; then
		idealswap=0
	elif [ $idealswap -le 67108864 ]; then
		idealswap=67108864
	fi
	unset sysram idealram
}

use_free () {
	# Alloc free space for boot,swap,root using default sizes
	# Arguments: [hdx [hdx [...]]]
	bootsize=5242880		# 5 MB
	calc_ideal_swap
	swapsize=$idealswap
	# Try to use a HD where /boot can be near the start of the disk; prefer
	# smaller disks
}

use_all () {
	# Wipe disks and use_free
	# Arguments: [hdx [hdx [...]]]
	false;	
}

find_percent () {
	# Convert percentage to byte number
false;
}

scale_hd () {
	# Scale HD ($2) into $1 size/percent
false;
}

calc_ideal_swap	# Let's have $idealswap set prior to hdconfig script

. /.ingen/hdconfig

unset use_free calc_ideal_swap

debug WARNING: Not implemented!
# /mnt/gentoo should be setup and clean
