#!/bin/bash
source ingen-func	# Function and variable declarations

debug Step 1: Setup partitions
source ingen-1
debug Step 2: Copy system, unmerging disabled pkgs live
source ingen-2
debug Step 3: Create users
source ingen-3
debug Step 4: Copy network configuration
source ingen-4
debug Step 5: Copy printer configuration
source ingen-5
debug Step 6: Configure time stuff
source ingen-6
debug Step 7: Monitor configuration changes
source ingen-7
# TODO: Keep /mnt/gentoo/$INGEN_DATA up to date when partitioning done?
