#!/bin/bash
# Step 4: Copy network configuration
# Is there anything I'm missing here? Seems too easy :)
debugoutput											\
	cp -vfra /etc/{conf.d/net*,resolv.conf,hosts}	\
			$SYSROOT/etc/conf.d/
debugoutput
	cp -vfra /home/luke-jr/.kde/share/config/kppprc

# TODO: autodetect when PCMCIA is needed for rc scripts?

