#!/bin/bash
source ingen-func	# Function and variable declarations

debug Step 1: Setup partitions
source ingen-1
debug Step 2: Copy system, unmerging disabled pkgs live
source ingen-2
debug Step 3: Create users
	# should this be moved to a seperate app so it can be done during copy?
source ingen-3
# Old Steps 4-6 have been discarded :)
debug New Step 6: Pivot root to harddrive
debug Step 7: Monitor configuration changes
source ingen-7
# TODO: Keep /mnt/gentoo/$INGEN_DATA up to date when partitioning done?
# use contents of overlay dir for this :)
