#!/bin/bash
INGEN_DATA=/.ingen
SYSROOT=/mnt/gentoo

 debug() { [  $DEBUG ] && echo DEBUG: "$@"; }
sdebug() { [ $SDEBUG ] && echo DEBUG: "$@"; }
pushvar() {	eval "$1_stack=\"\$$1:\$$1_stack\""; }
popvar() {
	var="$1"	svar="$1_stack"
	eval "$var=\"\`echo \"\$$svar\" | sed 's%:.*\$%%'\`\""
	eval "$svar=\"\`echo \"\$$svar\"| egrep -o ':.*\$' | cut -b 2-\`\""
	eval "if test \"\$$svar\" == \"\"; then unset \$$svar; fi"
}
outnull() {
	"$@" >/dev/null 2>&1
}
