#!/bin/bash
if [ "$#$1" != "1LaunchInGen" ]; then
	echo "You really don't want to run this..."; exit; fi
# Pivot root to harddrive
debug WARNING: Not implemented!
exit

#can't test pivot_root root :(
