#!/bin/bash
# Step 1: TODO: partitioning
# Setup functions for script
calc_ideal_swap () {
	# Find out how much RAM they got
	sysram="`grep 'Mem:' /proc/meminfo | { read a b c; echo $b; }`"
	idealram="268435456"
	let idealswap=$idealram-$sysram
	if [ $idealswap -le 33554432 ]; then
		idealswap=0
	elif [ $idealswap -le 67108864 ]; then
		idealswap=67108864
	fi
}

use_free () {
	# Alloc free space for boot,swap,root
}

. /.ingen/hdconfig

unset use_free calc_ideal_swap

debug WARNING: Not implemented!
# /mnt/gentoo should be setup and clean
