#!/bin/bash
source ingen-func	# Function and variable declarations

debug 1/5: Setup partitions
source ingen-harddisk
debug 2/5: Copy system, unmerging disabled pkgs live
source ingen-software
debug 3/5: Create users
	# should this be moved to a seperate app so it can be done during copy?
source ingen-users
debug 4/5: Pivot root to harddrive
source ingen-pivot
debug 5/5: Monitor configuration changes
source ingen-monitor
# TODO: Keep /mnt/gentoo/$INGEN_DATA up to date when partitioning done?
# use contents of overlay dir for this :)
