#!/bin/bash
install -m0755 ${LIVECD_ROOT}/profiles/${CD_PROFILE}/x-setup ${CD_BUILDCHROOT}/usr/sbin/x-setup
install -m0755 ${LIVECD_ROOT}/profiles/${CD_PROFILE}/xinitrc ${CD_BUILDCHROOT}/root/.xinitrc
install -m0644 ${LIVECD_ROOT}/profiles/${CD_PROFILE}/XF86Config.* ${CD_BUILDCHROOT}/etc/X11/
tar -jxvf ${LIVECD_ROOT}/profiles/${CD_PROFILE}/aux-files/root.tar.bz2 -C ${CD_BUILDCHROOT}/ || die
