#!/bin/bash
#this xinitrc uses xrandr to detect the current resolution, and then sets the appropriate
#resolution.
REALX=`xrandr | grep "^\*" | awk '{ print $2 }'`
REALY=`xrandr | grep "^\*" | awk '{ print $4 }'`
OK=0
for NEWRES in 1600x1200 1280x1024 1280x960 1024x768 800x600 640x480 512x384 320x200
do

	NEWX=${NEWRES%%x*}
	NEWY=${NEWRES##*x}
	echo $NEWRES
	if [ $NEWX -gt $REALX ]
	then
		#the NEWX is higher than our current Y res; continue....
		continue
	fi
	echo REALY $REALY
	echo NEWY $NEWY
	if [ $REALY -lt $NEWY ]
	then
		#our current Y res is less than our NEWY; continue...
		continue
	fi
	#if we've gotten here, we want to use NEWXxNEWY as our aa resolution
	OK=1
	break


done
#tweak configuration file here
if [ "$OK" = "0" ]
then
	echo ".xinitrc: couldn't identify proper Xfree resolution; exiting."
	exit 1
fi
startkde
