.\"                                      EMACS: -*- nroff -*-
.\" $Id: netdiag.8,v 1.1 2006/03/11 05:39:20 vapier Exp $
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH NETDIAG 8 "March 21, 2005" "Scyld\*(Tm Beowulf"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
netdiag \- Network adapter hardware-level diagnostics
.SH SYNOPSIS
.B nicname-diag
.RI [ options ]
.SH DESCRIPTION
This manual page documents briefly the
.B ethernet-diag
network adapter setup and diagnostic commands.
Addition documentation is available from http://scyld.com/diag/index.html.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invoke bold face and italics, 
.\" respectively.
\fBnetdiag\fP is a set of hardware diagnostic and setup programs for
network adapters, primarily Ethernet and Ethernet-like adapters.
.SH OPTIONS
\fBnetdiag\fP programs need a single dash (´-´) in front of the option.
For options without parameters, multiple options may be concatenated
after a single dash.
A summary of options is as follows.

.TP
.B \-# N
Describe or perform operations only the the Nth adapter found.

.TP
.B \-a
Show all chip registers.  If the adapter is active, this option may
need to be combined with the '-f' option.

.TP
.B \-B
Show the contents of the Flash boot ROM.

.TP
.B \-D
Increase the debugging level.  This may be used to understand why the
diagnostic program is not detecting an adapter.

.TP
.B \-e
Show the EEPROM contents.  Doubling or tripling this option,  "-ee", shows
additional details.
.TP
.B \-E
Do an Emergency rewrite of a completely corrupted EEPROM.  This option
is not implemented for some adapter types, and the internal table is likely
to be incorrect for the specific adapter version.  This option should never be
used without reading the diagnostic source code and understanding the
implications of different board versions.

.TP
.B \-f
Force operations.  This option causes the diagnostic program to
proceed even if it detects that the adapter is currently active.

.TP
.B \-F media-type
Set the transceiver selection to the specified type.  Valid media
types are 10baseT, 10base2, 10base5, AUI.

.TP
.B \-G value
Set a adapter-specific General-purpose value.
This is typically used to modify or control the LED setting.

.TP
.B \-H 01:23:45:67:89:AB
Provide a new station ("Hardware") MAC address for the adapter.

.TP
.B \-L loadfile
  Write the Flash boot ROM with the contents of LOADFILE.
.TP
.B \-m
Show MII registers.  With many diagnostic programs "-mm" shows
additional details or polls the MII registers for one minute, reporting any
status changes.

.TP
.B \-p I/O-port
Specify the I/O port at which to find a single card.  This option is
primarily for ISA and CardBus adapters, but may be useful when a PCI
adapter is not recognized.  This option is usually used with
'-t chip-type'.

.TP
.B \-q
Quiet mode.  But diagnostic program tend to be verbose anyway.

.TP
.B \-S savefile
Save the Flash boot ROM contents into SAVEFILE.

.TP
.B \-t type-index
Specify the chip type when it cannot be detected.  Using an invalid
index e.g. '-1' will cause a list of chip types to be emitted. This option is
usually used with '-p port-base'.

.TP
.B \-T
Run a functionality test appropriate to the chip, typically a memory
or loopback test.

.TP
.B \-v
Increase the verbosity level.  Additional "-v" options increase the
level further.

.TP
.B \-V
Show the program version information.

.TP
.B \-w
Write the EEPROM with the specified updated values.  Without this
option the program will merely report what it would write.

.TP
.B \-?
Emit usage information.

.SH SEE ALSO
.BR ether-wake (8), mii-diag (8), mii-tool (8).
.br
.SH KNOWN BUGS
Not all programs allow writing the EEPROM without modifying the source
code to explicitly enable this feature.  Remember, this permanently
modifies the configuration, losing the old information as part of the
process.  Some modifications are difficult or impossible to reverse.

Some diagnostic programs do not implement Flash operations even when the
adapters are physically capable of updating the EEPROM.  The adapter
must permit Flash updates from its regular address space, rather than
require access through the PCI Boot Rom address space.  Linux does not
allow user-level programs to memory map the Boot ROM space.

.SH AUTHOR
This manual page was written by Donald Becker for the Scyld(\*(Tm) Beowulf System.
