#!/bin/sh
#
# Pieter Van den Abeele <pvdabeel@gentoo.org>
# (C) 2002 2003 2004 Pieter Van den Abeele
# Distributed under the GPL v.2

PATH=/usr/sbin:/usr/bin:/sbin:/bin

mount -o remount,rw /

mount proc -t proc /proc
mount tmpfs -t tmpfs /mnt/live

echo "0" >/proc/sys/kernel/printk

findmount() {
    CDROM="/dev/cdroms/${1}"
    mount -t iso9660 -r $CDROM /mnt/live/mnt/cdrom >/dev/null 2>&1
    sleep 5 # this should become dynamic 
    if [ -d /mnt/live/mnt/cdrom/live.gcloop ]; then
      umount /mnt/live/mnt/cdrom
      echo "LRC: live.iso not found on $CDROM"
      sleep 5
      shift
      findmount $*
    else
      # uncompressed live environments.
      
      # losetup /dev/loop/0 /mnt/live/mnt/cdrom/live.iso
      # mount -t iso9660 -r /dev/loop/0 /mnt/live/mnt/iso/
      # insmod /lib/modules/misc/cloop.o file=/mnt/live/mnt/cdrom/live.gcloop
      
      # compressed live environments
      
      mknod /dev/cloop b 240 0
      insmod /lib/modules/misc/cloop.o file=/mnt/live/mnt/cdrom/live.gcloop
      mount -o ro -t ext2 /dev/cloop /mnt/live/mnt/iso/
    fi
}

cd /mnt/live
mkdir /mnt/live/mnt        
mkdir /mnt/live/mnt/iso    
mkdir /mnt/live/mnt/cdrom  
mkdir /mnt/live/mnt/initrd 
mkdir /mnt/live/mnt/.init.d

findmount cdrom0 cdrom1 cdrom2 cdrom3 cdrom4

ln -s mnt/iso/bin  .
ln -s mnt/iso/lib  .
ln -s mnt/iso/sbin .
ln -s mnt/iso/boot .
ln -s mnt/iso/usr  .
ln -s mnt/iso/opt  .

mount tmpfs -t tmpfs /mnt/live/lib/modules
cp -a /lib/modules/* /mnt/live/lib/modules

mkdir proc etc var
cd mnt/iso
cp -a dev home root tmp etc /mnt/live/
chmod 1777 /mnt/live/tmp

cd /mnt/live/var
ln -s ../mnt/iso/var/db .
ln -s ../mnt/iso/var/empty .
cd ../mnt/iso/var
cp -a cache lib lock log run spool tmp ../../../var/

echo "6" >/proc/sys/kernel/printk

umount /proc
cd /mnt/live
pivot_root . mnt/initrd
# /bin/mount -o bind ./mnt/initrd/dev /dev # bug #17009
mount devfs -t devfs /dev
exec chroot . /sbin/init <dev/console >dev/console 2>&1
