#!/usr/bin/python
import catalyst_util,string,sys
#with no args, returns a full list of subarches. With
#one arg, will exit 0 if subarch is valid, else 1.
if len(sys.argv)==1:
	myarches=catalyst_util.subarches
	myarches.sort()
	print "SUBARCHES=\""+string.join(myarches," ")+"\""
	sys.exit(0)
else:
	if sys.argv[1] in catalyst_util.subarches:
		sys.exit(0)
	else:
		sys.exit(1)

