#!/usr/bin/python
import portage
import catalyst_util
import sys
import string

if len(sys.argv) != 2:
	sys.exit(1)

results=catalyst_util.compile_defaults(sys.argv[1])
if results==None:
	sys.exit(1)
print "MAINARCH=\""+results[0]+"\""
print "CFLAGS=\""+results[1]+"\""
print "CHOST=\""+results[2]+"\""

myu=portage.settings["GRP_STAGE23_USE"]+" "+string.join(results[3]," ")
if myu[-1]==" ":
	myu=myu[:-1]

print "BUILD_USE=\""+myu+"\""
print "CONF_USE=\""+string.join(results[3]," ")+"\""
