#!/bin/bash
################################################
# quick script to roll a new genpatches release.
################################################

dir="${@}"
[ -z "${dir}" ] && dir="$(find ./ -type d -and -not -iname "*CVS*" -and -not -iname "output" | tail -n 1)"

#file_base="${dir/\.\//}-base.tar.bz2"
#file_extras="${dir/\.\//}-extras.tar.bz2"
#file_experimental="${dir/\.\//}-experimental.tar.bz2"

file="${dir/\.\//}.tar.bz2"

#[ -n "$(find ${dir}/[012]* 2>/dev/null)" ] && tar -cvjf ${file_base} ${dir}/[012]* --exclude=CVS
#[ -n "$(find ${dir}/[34]* 2>/dev/null)" ] &&  tar -cvjf ${file_extras} ${dir}/[34]* --exclude=CVS
#[ -n "$(find ${dir}/5* 2>/dev/null)" ] &&     tar -cvjf ${file_experimental} ${dir}/5* --exclude=CVS

[ -n "$(find ${dir}/* 2>/dev/null)" ] &&     tar -cvjf ${file} ${dir}/* --exclude=CVS

echo
echo Roll complete.
for i in $(find ./ -type f -iname "${dir/\.\//}-*.tar.bz2" -maxdepth 1)
do
	md5=$(md5sum ${i})
	echo "Produced: ${i/\.\//}"
	echo "          md5: ${md5/\ */}"
done
echo

[ ! -d "output" ] && mkdir output
mv ${dir/\.\//}.tar.bz2 output
