#!/bin/bash
# $Header: /var/cvsroot/gentoo/users/wolf31o2/keyword,v 1.1 2006/05/25 22:12:51 wolf31o2 Exp $

usage() {
	echo "$(basename ${0}): <keyword> <input file>"
}

if [ -z "${1}" -o -z "${2}" ]
then
	usage
	exit 0
fi

cvsroot=/var/cvsroot/gentoo-x86

cpv=$(cat ${2} | grep -v "^#" | grep -v "^[[:space:]]*#")
packages=$(cat ${2} | grep -v "^#" | grep -v "^[[:space:]]*#" | cut -d" " -f1 | sort -u)

echo "${cpv}" > /tmp/cpv.txt
#echo "${packages}" > /tmp/packages.txt

for package in ${packages}
do
	for version in $(grep "${package} " /tmp/cpv.txt | cut -d" " -f2)
	do
		ebuild="$(echo ${package} | cut -d"/" -f2)-${version}"
		cd ${cvsroot}/${package}
		ekeyword ${1} ${ebuild}.ebuild
	done
done

