#!/bin/bash

if [ -z $1 ]; then
   echo "Usage: zipit <version-number>"
   exit 1
fi

VER="$1"
DIR=/tmp/plugin-${VER}

mkdir ${DIR}

cp src/* ${DIR}
cp doc/* ${DIR}
cp install/* ${DIR}

cd /tmp
zip -r plugin-${VER}.zip plugin-${VER}
cd -
mv /tmp/plugin-${VER}.zip .

rm -rf ${DIR}
