#!/usr/bin/perl

# WARNING
#
# THIS IS A WORK IN PROGRESS. ALL CODE IS SUBJECT TO CHANGE.
# And cleaning ;0
#
# This is a test framework for a graphical version of bugger
#
# mcummings@gentoo.org
#
package main;
use Tk;
use Tk::ToolBar;
use Tk::HList;
use Tk::ItemStyle;
use bugger;

use vars qw/$TOP/;

my $mw = new MainWindow;
my $tb = $mw->ToolBar(
    qw/-movable 1 -side top
      -indicatorcolor blue /
);

$tb->ToolButton(
    -text    => 'Button',
    -tip     => 'tool tip',
    -command => sub { print "hi\n" }
);
$tb->ToolLabEntry(
    -label     => 'Search Bugs',
    -labelPack => [
        -side   => "left",
        -anchor => "w"
    ],
    -width => 20,
);

my $tb2 = $mw->ToolBar;
$tb2->ToolButton(
    -image   => 'navforward22',
    -tip     => 'forward',
    -command => \&forward
);
$tb2->separator;
$tb2->ToolButton(
    -image   => 'navhome22',
    -tip     => 'home',
    -command => \&home
);
$tb2->ToolButton(
    -image   => 'actreload22',
    -tip     => 'reload',
    -command => \&reload
);
$tb2->ToolButton(
   -image    => 'actexit22',
   -tip      => 'quit',
   -command  => \&quit
);
my $hlist = $mw->Scrolled(qw/HList
	-columns 3
	-width 70
	-command main::launch_win/)->pack(qw/-expand yes -fill both/);
	#-command launch_win/)->grid(qw/-sticky ns/); $hlist->pack(qw/-expand yes -fill both/);
   my (@red,@blue,@black);
   $red[1]  = $hlist->ItemStyle('text', -foreground=>'#800000');
   $red[2]  = $hlist->ItemStyle('text', -foreground=>'#800000', -background=>'#fbdaffffb603');
   $blue[1] = $hlist->ItemStyle('text', -foreground=>'#000080');
   $blue[2] = $hlist->ItemStyle('text', -foreground=>'#000080', -background=>'#fbdaffffb603');
   $black[1] = $hlist->ItemStyle('text', -foreground=>'#000000000000', -background=>'#ffffffffffff');
   $black[2] = $hlist->ItemStyle('text', -foreground=>'#000000000000', -background=>'#fbdaffffb603');
   my $header;
   $header = $hlist->addchild("");
   $hlist->itemCreate($header, 0, -itemtype=>'text', -text=>"BugID", -style=>$black[1]);
   $hlist->itemCreate($header, 1, -itemtype=>'text', -text=>"Priority", -style=>$black[1]);
   $hlist->itemCreate($header, 2, -itemtype=>'text', -text=>"Description", -style=>$black[1]);

   
   my %results = bugger::list_bugs('mcummings@gentoo.org');
   my $bug_no = scalar(keys %results);
   my $colorchange = 1;
   for (my $key = 1; $key <=$bug_no; $key++){
   my $entry;
       $entry = $hlist->addchild("");
       $hlist->itemCreate($entry, 0, -itemtype=>'text',
                -text=>"$results{$key}{'BugID'}", -style=>$red[$colorchange]);
       $hlist->itemCreate($entry, 1, -itemtype=>'text',
                -text=>"$results{$key}{'Priority'}", -style=>$blue[$colorchange]);
       if (length($results{$key}{'Description'}) >=48)
       	{ substr($results{$key}{'Description'},48) = "..."}
       $hlist->itemCreate($entry, 2, -itemtype=>'text',
                -text=>"$results{$key}{'Description'}", -style=>$blue[$colorchange]);
	if ($colorchange == 2) {$colorchange = 1}
	else {$colorchange = 2}
}	
	
MainLoop;

sub forward { print "going totally forward\n" }

sub launch_win {
my $incoming = shift;

my $bugID = $results{$incoming}{'BugID'};
my $mw2 = new MainWindow;
my $tb = $mw2->ToolBar(
    qw/-movable 1 -side top
      -indicatorcolor blue /
);
$tb->ToolButton(
   -image    => 'actexit22',
   -tip      => 'quit',
   -command  => [$mw2 => 'destroy']
);
 my $text = $mw2->Scrolled(qw/Text -setgrid true -scrollbars e/);
$text->pack(qw/-expand yes -fill both/);
my @bugtext = bugger::show_bug($bugID);
 $text->insert('0.0', "@bugtext");
    $text->mark(qw/set insert 0.0/);
	
MainLoop;
}

sub quit { print "Thank you for using bugger-tk\n\n";  exit() }
