#!/bin/sh
# Copyright 1999-2004 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo/src/netboot-base/sbin/rc,v 1.3 2005/01/10 14:22:22 gmsoft Exp $

. /sbin/functions.sh

export PATH="/bin:/sbin:${PATH}"

case $1 in
	# Boot time
	sysinit)

		echo
		echo -e "${GOOD}Gentoo Linux${GENTOO_VERS}; ${BRACKET}http://www.gentoo.org/${NORMAL}"
		echo -e " Copyright 1999-2004 Gentoo Foundation; Distributed under the GPL"
		echo

		ebegin "Setting hostname to netboot"
		hostname netboot
		eend $? "Failed to set hostname"

		ebegin "Remouting / read-write"
		mount -n -o rw,remount /
		eend $? "Failed to remount /"

		ebegin "Mounting proc at /proc"
		mount -n -t proc none /proc
		eend $? "Failed to mount /proc"

		if grep -q sysfs /proc/filesystems
		then
			mkdir -p /sys
			ebegin "Mounting sysfs at /sys"
			mount -n -t sysfs none /sys
			eend $?
		fi

		mkdir -p /dev/pts /dev/shm
		ebegin "Mounting other filesystems"
		mount -a
		eend $? "Failed to mount the others filesystems"

		ln -sf /proc/mounts /etc/mtab

		ebegin "Starting devfsd"
		devfsd /dev > /dev/null 2>&1
		eend $? "Failed to start devfsd"
		
		ebegin "Starting syslogd"
		syslogd -m 0
		eend $? "Failed to start logger"

		cat /etc/motd

		# Sleep 1 sec to allow motd to display correctly on serial console
		sleep 1

		;;

	# Reboot time
	reboot)

		echo

		# Stopping syslog
		ebegin "Stopping syslogd"
		kill -15 `my_pidof syslogd` > /dev/null 2>&1
		eend $? "Failed to stop logger"

		# Stopping devfsd 
		ebegin "Stopping devfsd"
		kill -15 `my_pidof devfsd` > /dev/null 2>&1
		eend $? "Failed to stop devfsd"

		# Umount everything
		ebegin "Unmounting all filesystems"
		umount -a -r > /dev/null 2>&1
		ret=$?
		eend ${ret} "Failed to unmount filesystems"
		if [ ${ret} -ne 0 ]
		then
			ebegin "Retrying unmount"
			umount -a -r > /dev/null 2>&1
			eend ${ret} "Failed to unmount again; giving up"
		fi

		;;

	*)
esac
