#!/bin/bash
# Copyright 1999-2005 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo/src/livecd-tools/openglify,v 1.7 2006/07/20 21:34:03 wolf31o2 Exp $

#This script is designed to tweak the system for opengl-update
#set up our flexible opengl stuff:

#move symlinks to a malleable /etc/opengl directory.
install -d test/lib/modules/extensions

rm -f /usr/lib/libGL{,core}.{a,so}* > /dev/null 2>&1
rm -f /usr/lib/modules/extensions/libglx* > /dev/null 2>&1
rm -f /usr/lib/xorg/modules/extensions/libglx* > /dev/null 2>&1

ln -sf /etc/opengl/lib/libGL.so /usr/lib/libGL.so
ln -sf /etc/opengl/lib/libGL.so.1 /usr/lib/libGL.so.1
ln -sf /etc/opengl/lib/libGLcore.so /usr/lib/libGLcore.so
ln -sf /etc/opengl/lib/libGLcore.so.1 /usr/lib/libGLcore.so.1
if [ -d /usr/lib/modules/extensions ]
then
	ln -sf /etc/opengl/lib/modules/extensions/libglx.so \
		/usr/lib/modules/extensions/libglx.so
	ln -sf /etc/opengl/lib/modules/extensions/libglx.a \
		/usr/lib/modules/extensions/libglx.a
elif [ -d /usr/lib/xorg/modules/extensions ]
then
	ln -sf /etc/opengl/lib/modules/extensions/libglx.so \
		/usr/lib/xorg/modules/extensions/libglx.so
	ln -sf /etc/opengl/lib/modules/extensions/libglx.a \
		/usr/lib/xorg/modules/extensions/libglx.a
fi

