#!/bin/bash
# Copyright 1999-2004 Gentoo Technologies, Inc.
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo/src/livecd-tools/openglify,v 1.1 2004/05/14 13:27:25 wolf31o2 Exp $

#This script is designed to tweak the system for CD-based opengl-update
#set up our flexible opengl stuff:

#move symlinks to a malleable /etc/opengl directory.
install -d /etc/opengl
mv /usr/lib/libGL.* /etc/opengl/
mv /usr/lib/libGLcore.* /etc/opengl/
ln -sf /etc/opengl/libGL.so /usr/lib/libGL.so
ln -sf /etc/opengl/libGL.so.1 /usr/lib/libGL.so.1
ln -sf /etc/opengl/libGLcore.so /usr/lib/libGLcore.so
ln -sf /etc/opengl/libGLcore.so.1 /usr/lib/libGLcore.so.1
mv /usr/X11R6/lib/libMesaGL.so /etc/opengl/
ln -sf /etc/opengl/libMesaGL.so /usr/X11R6/lib/libMesaGL.so
for x in libglx.a libglx.so
do
	if [ -e /usr/X11R6/lib/modules/extensions/\${x} -o -L \
	/usr/X11R6/lib/modules/extensions/\${x} ] 
	then
		mv /usr/X11R6/lib/modules/extensions/\${x} /etc/opengl/
	fi
	ln -s /etc/opengl/\${x} \
	/usr/X11R6/lib/modules/extensions/\${x}
done
