#!/sbin/runscript
# Copyright 1999-2004 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo/src/livecd-tools/spind.init,v 1.3 2004/11/19 16:11:24 wolf31o2 Exp $

depend() {
	before local
}

start() {
	ebegin "Starting spin daemon"
	start-stop-daemon --start --quiet --exec /usr/sbin/spind
	eend $?
}

stop() {
	ebegin "Stopping spind"
	start-stop-daemon --stop --quiet --exec /usr/sbin/spind
	eend $?
}
