#!/bin/bash
# Copyright 1999-2004 Gentoo Foundation
# NO WARRANTY; licensed under the GNU GPL2

CDSIZE=$(($(df -P | grep cdrom | head -n 1 | awk '{print $2}') - 256))
[ -z "${CDSIZE}" ] && echo '>>> Unknown CD size...' && exit 1

echo ">>> CD size: $(($CDSIZE + 256)) K"
while true
do
	dd if=/dev/cdrom of=/dev/null bs=1K count=1 skip=$(($RANDOM * $CDSIZE / 32768)) 2>/dev/null
	sleep 30
done
