#!/bin/bash
# Copyright 1999-2003 Gentoo Technologies, Inc.
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo/users/zhen/catalyst/catalyst,v 1.35 2003/10/13 00:14:41 zhen Exp $

VERSION="2.2"

source /sbin/functions.sh
source include/functions.sh
source include/build_functions.sh
[ -e files/catalyst.conf ] && source files/catalyst.conf || die "Config file files/catalyst.conf not found."


rm -f /tmp/catalyst-subarches
include/catalyst-subarches > /tmp/catalyst-subarches
source /tmp/catalyst-subarches

SNAPBALL=${SNAPDIR}/portage-${4}.tar.bz2

# unset so chroot doesn't get our custom setting
unset PORTDIR DISTDIR
[ ! -e "$MY_PORTDIR" ] && die "Portage dir $MY_PORTDIR not found, exiting."
[ ! -e "$MY_DISTDIR" ] && die "Distdir $MY_DISTDIR not found; exiting."

MY_DIST_LOCALS=${BASEDIR}/dists/${4}
install -d $MY_DIST_LOCALS
[ "$TMPDIR" = "" ] && CHROOTDIR="/var/tmp/catalyst/build/stage-${2}-${4}" || CHROOTDIR="$TMPDIR/stage-${2}-${4}"

MYPROFILEDIR="/usr/portage/profiles/${BUILDTYPE}-${MAINARCH}-${MAINVERSION}"

#umount() {
#	einfo "Unmounting..."
#	umount_all

#} #end umount
	
if [ "`whoami`" != "root" ]
then
	eerror "$0: This script requires root privileges to operate."
	exit 1
fi
	
if [ -z ${MYPROFILEDIR} ]
then
	eerror "!!! Profile missing! You must 'emerge sync'"
	exit 1
fi

case "$1" in
	"-h"|"--help")
		usage
		exit 1
	;;

	"snap")
		snap $2
		exit 0
	;;
	
	"umount")
		umount
		exit 0
	;;

	"enter")
		enter_chroot
		exit 0
	;;

	*)
		# basically we try to remove $1 from $SUBARCHES
        # then test if it did get removed or not
        SUBARCHES_TEST="`echo ${SUBARCHES} | sed "s/\W${1}\>//g;s/^${1}\>//"`"
        if [ ! "${SUBARCHES_TEST}" = "${SUBARCHES}" ]
		then
			start_build $1 $2 $3 $4
			exit 0
		else
			usage
			exit 1
		fi
	;;
esac

# vim ts=4
