At the prompt the following labels are valid
ex: label option

800     =       800x600 framebuffer mode

1024    =       1024x768 frambuffer mode (default)

1280    =       1280x1024 framebuffer mode

nofb    =       framebuffer mode disabled

smp     =       loads a smp kernel in noframebuffer mode

acpi    =       enables acpi=on + loads acpi modules during init

memtest =       boots the memory testing program
