#!/bin/bash
echo "$CD_HOSTNAME" > ${CD_BUILDCHROOT}/etc/hostname || die
#modprobe has a bug and auto-adds a "above hid keybdev mousedev" line to it's internel configuration.
#this fixes it....
echo "above hid" > ${CD_BUILDCHROOT}/etc/modules.d/hidfix
install -d ${CD_BUILDCHROOT}/root/.irssi
cp ${LIVECD_ROOT}/profiles/${CD_PROFILE}/aux-files/config ${CD_BUILDCHROOT}/root/.irssi || die
rm ${CD_BUILDCHROOT}/etc/init.d/iptables
cp ${CD_BUILDCHROOT}/etc/init.d/net.eth0 ${CD_BUILDCHROOT}/etc/init.d/net.eth1
cp ${LIVECD_ROOT}/profiles/${CD_PROFILE}/aux-files/modules ${CD_BUILDCHROOT}/etc/init.d || die
cp ${LIVECD_ROOT}/profiles/${CD_PROFILE}/aux-files/checkroot ${CD_BUILDCHROOT}/etc/init.d || die
cp ${LIVECD_ROOT}/profiles/${CD_PROFILE}/aux-files/md ${CD_BUILDCHROOT}/etc/init.d || die
cp ${LIVECD_ROOT}/profiles/${CD_PROFILE}/aux-files/autoconfig ${CD_BUILDCHROOT}/etc/init.d || die
cp ${LIVECD_ROOT}/profiles/${CD_PROFILE}/aux-files/local ${CD_BUILDCHROOT}/etc/init.d || die
cp ${LIVECD_ROOT}/profiles/${CD_PROFILE}/aux-files/fstab ${CD_BUILDCHROOT}/etc || die
cp ${LIVECD_ROOT}/profiles/${CD_PROFILE}/net-setup ${CD_BUILDCHROOT}/usr/sbin || die
cp ${LIVECD_ROOT}/profiles/${CD_PROFILE}/aux-files/profile ${CD_BUILDCHROOT}/etc || die
cp ${LIVECD_ROOT}/profiles/${CD_PROFILE}/aux-files/net ${CD_BUILDCHROOT}/etc/conf.d || die
rm -f ${CD_BUILDCHROOT}/lib/evms/libe2fsim.1.2.1.so
rm -f ${CD_BUILDCHROOT}/usr/share/hwdata/pci.ids
rm -f ${CD_BUILDCHROOT}/usr/share/hwdata/usb.ids
ln -s /usr/share/misc/pci.ids ${CD_BUILDCHROOT}/usr/share/hwdata/pci.ids
ln -s /usr/share/misc/usb.ids ${CD_BUILDCHROOT}/usr/share/hwdata/usb.ids
cp ${LIVECD_ROOT}/profiles/${CD_PROFILE}/aux-files/install.txt ${CD_BUILDCHROOT}/ || die
echo usbcore >> ${CD_BUILDCHROOT}/etc/hotplug/blacklist
chmod +x ${CD_BUILDCHROOT}/usr/sbin/net-setup  || die
mymotd=${LIVECD_ROOT}/profiles/${CD_PROFILE}/motd
[ -e $mymotd ] && cp $mymotd ${CD_BUILDCHROOT}/etc
echo "CDBOOT=1" >> ${CD_BUILDCHROOT}/etc/rc.conf || die
echo "127.0.0.1 cdimage localhost" > ${CD_BUILDCHROOT}/etc/hosts || die
cp ${LIVECD_ROOT}/profiles/${CD_PROFILE}/aux-files/inittab ${CD_BUILDCHROOT}/etc || die
mount_all
cat > $CD_BUILDTEMP/chroot-clean << EOF
#!/bin/bash
source /etc/profile
#do our hid fix...
modules-update
cd /usr/src/linux
#produce correct module dependency information
make _modinst_post
rc-update add autoconfig default
rc-update add md default
if [ -e /etc/init.d/metalog ]
then 
rc-update add metalog default
elif [ -e /etc/init.d/sysklogd ]
then
rc-update add sysklogd default
fi
#remove standard keymap support:
rc-update del keymaps
rc-update del consolefont
rc-update del iptables
rc-update add distcc default
update-modules
EOF
chmod +x $CD_BUILDTEMP/chroot-clean
chroot $CD_BUILDCHROOT /tmp/livecd/chroot-clean
[ $? -ne 0 ] && chroot_die "chroot-clean failure"
umount_all
rm -rf ${CD_BUILDCHROOT}/etc/localtime 
cp ${CD_BUILDCHROOT}/usr/share/zoneinfo/GMT ${CD_BUILDCHROOT}/etc/localtime || die

if [ -e "${LIVECD_ROOT}/profiles/${CD_PROFILE}/openglify" ]
then
	source ${LIVECD_ROOT}/profiles/${CD_PROFILE}/openglify
fi

find ${CD_BUILDCHROOT}/lib/modules -name modules.dep |xargs touch

