#!/bin/sh

# Copyright Gentoo Technologies, Inc and Pieter Van den Abeele <pvdabeel@gentoo.org> 2003
# Distributed under the GPL v2

source /etc/profile
 
source /livecd/src/globals
source /livecd/src/settings
source /livecd/config/livecd.conf
source /livecd/config/make.conf

cp /livecd/config/make.conf /etc/make.conf

env-update || true

trap "err 'Aborted on users request' ; exit 1" INT

function INSIDE_ERROR() {
	err "${*}"
	exit 1
}

msg "Upgrading current system to the latest"

if [ "${_UPDATE_}" != "no" ]; then
	emerge --pretend --update world
	waiting
	emerge --update -k world
fi

msg "Building extra stuff inside chrooted environment"

echo "DEBUG:"
echo "----------------"
echo "$_USE_"
echo "$_EMERGE_"
echo "----------------"


if [ "${_EMERGE_}" != "" ]; then 
	emerge --pretend -n -k -b ${_EMERGE_}
	waiting
	emerge           -n -k -b ${_EMERGE_} || INSIDE_ERROR "emerge failed"
fi

if [ -e /etc/init.d/metalog ]; then
	rc-update add metalog default
elif [ -e /etc/init.d/sysklogd ]; then
 	rc-update add sysklogd default
fi

if [ -e /etc/init.d/vcron ]; then
	rc-update add vcron default
elif [ -e /etc/init.d/sysklogd ]; then
	rc-update add vcron default
fi

msg "Building finished"

update-modules 
env-update
