#!/bin/sh

# Copyright Gentoo Technologies, Inc and Pieter Van den Abeele <pvdabeel@gentoo.org> 2003
# Distributed under the GPL v2

# Cleans out the live environment to gain some extra free space (at the cost of functionality)
# Some of this code has been copied from Daniel Robbins livecd script. (such as for example the 
# zapmost function, which has been slightly adapted and moved into globals)

source /etc/profile
 
source /livecd/src/globals
source /livecd/src/settings
source /livecd/config/livecd.conf
source /livecd/config/make.conf

trap "err 'Aborted on user request' ; exit 1" INT

function INSIDE_ERROR() {
	err "${*}"
	exit 1
}

msg "Cleaning inside chrooted environment"

env-update

rm -rf /livecd
rm -rf /etc/resolv.conf
rm -rf /usr/src/linux*

[ "${_DEVELOPER_}" = "yes" ] &&  exit 0

[ "${_UNMERGE_}" != "" ] &&  emerge -C ${_UNMERGE_}
emerge -C linux-headers

touch /usr/lib/gcc-lib/*/*/*.so*
touch /usr/lib/libstdc++*
touch /etc/env.d/??gcc*

for i in  /var/tmp \
          /var/empty \
          /var/db \
          /var/cache \
          /var/lock \
          /tmp \
          /usr/X11R6/man \
          /usr/X11R6/lib/X11/etc \
          /usr/X11R6/lib/X11/doc \
          /usr/X11R6/lib/X11/config \
          /usr/X11R6/include \
          /usr/share/zoneinfo \
          /usr/share/unimaps \
          /usr/share/texinfo \
          /usr/share/swat \
          /usr/share/state \
          /usr/share/ss \
          /usr/share/rfc \
          /usr/share/man \
          /usr/share/info \
          /usr/share/gnupg/FAQ \
          /usr/share/gettext \
          /usr/share/doc \
          /usr/share/dict \
          /usr/share/aclocal \
          /usr/lib/portage \
          /usr/info \
          /usr/include \
          /usr/doc;
do 
 	echo " --- Cleaning up in ${i}"
	rm -rf ${i}/* ${i}/.* >/dev/null 2>/dev/null
done

rm -rf /sbin/sln
rm -rf /usr/share/gnupg/faq.html
rm -rf /usr/X11R6/bin/Xnest
rm -rf /usr/X11R6/bin/Xprt
rm -rf /usr/X11R6/bin/Xvfb
rm -rf /usr/lib/gcc-lib/*/*/libgcj*
rm -rf /usr/lib/python2.2/config 

zapmost /usr/share/terminfo l v n x             
zapmost /usr/share/terminfo/l linux             
zapmost /usr/share/terminfo/v vt100 vt102       
zapmost /usr/share/terminfo/x xterm xterm-color
zapmost /usr/share/locale C en_US               
zapmost /usr/X11R6/lib/X11/locale iso8859-1 iso8859-15 common en_US.UTF-8
zapmost /usr/share/misc magic
zapmost /usr/share/i18n/charmaps ISO-8859-1.gz ISO-8859-15.gz MAC-UK.gz MACINTOSH.gz MAC-SAMI.gz MAC-IS.gz MAC-CYRILLIC.gz
zapmost /usr/share/i18n/locales en_US nl_BE@euro nl_BE
zapmost /usr/lib/locale en_US
 
for i in bin lib opt sbin usr var ;
do
 	echo " --- doing ${i}"
	find /${i} -iname '*~'    -exec rm -f {} \;
 	find /${i} -iname '*.a'   -exec rm -f {} \;
done

find /etc               -iname '._*'      -exec rm -f {} \;
find /usr/lib/python2.2 -iname '*.py[co]' -exec rm -f {} \; 
find /usr/lib/perl5     -iname '*.pod'    -exec rm -f {} \;
find /usr/X11R6/include -iname '*.h'      -exec rm -f {} \;
 
[ ! -d /usr/share/vim/vim61/doc ] || find /usr/share/vim/vim61/doc/ -not -name help.txt -and -not -name intro.txt -and -not -name uganda.txt -and -not -name tags -exec rm -f {} \;

msg "Cleaning finished"

touch /tmp/.cleaned
