#!/bin/sh

# Copyright Gentoo Technologies, Inc and Pieter Van den Abeele <pvdabeel@gentoo.org> 2003
# Distributed under the GPL v2

# Builds the kernel and kernel modules - upgrades from stage1 to stage3 should no stage3 but 1 or 2 be given

source /etc/profile
 
source /livecd/src/globals
source /livecd/src/settings
source /livecd/config/livecd.conf

echo "USE=\"$_USE_\"" >> /livecd/config/make.conf
source /livecd/config/make.conf

cp /livecd/config/make.conf /etc/make.conf

env-update

trap "err 'Aborted on user request' ; exit 1" INT

function INSIDE_ERROR() {
	err "${*}"
	exit 1
}

if [ "${_TYPE_}" = "stage1" ]; then
	msg "Upgrading to stage 2"
	/scripts/bootstrap.sh || INSIDE_ERROR "bootstrap failed"
	_TYPE_="stage2"
fi 

if [ "${_TYPE_}" = "stage2" ]; then
 	msg "Upgrading to stage 3"
	emerge system         || INSIDE_ERROR "emerge system failed"
	_TYPE_="stage3"
fi

if [ "${_TYPE_}" = "stage3" ]; then
	if [ ! -f /usr/src/.OK ]; then
		msg "Building kernel"
		USE="-*" emerge --pretend -k -n ${_KERNEL_}
		USE="-*" emerge -k -n ${_KERNEL_}
		cp -rf /livecd/config/${_KERNEL_CONFIG_} /usr/src/linux/.config
		cd /usr/src/linux/
		(make oldconfig symlinks dep clean vmlinux modules modules_install && touch ../.OK) || INSIDE_ERROR "building kernel failed"
		cd /
		cp -rf /usr/src/linux/vmlinux    /boot/
		cp -rf /usr/src/linux/System.map /boot/
	fi
fi

msg "Kernel building finished"
