#!/bin/sh

PATH=/usr/sbin:/usr/bin:/bin:/sbin

CNT="category"

keymaps()   {
        while :
	do

	case $CNT in
	 "category") category
	  ;;
	 "Azerty") Azerty
	  ;;
	 "Dvorak") Dvorak
	  ;;
	 "Qwerty") Qwerty
	  ;;
	 "Qwertz") Qwertz
	  ;;
	 *) exit 0
	  ;;
 	esac
	
	done
}

category()  {

        echo

	CNT="`dialog\
           --title "SETUP :: KEYMAP" \
           --menu "\nPlease select a keyboard layout:\n"\
           20 60 12\
           Azerty ""\
           Dvorak ""\
	   Qwerty ""\
           Qwertz "" 2>&1`"
}

Azerty() {

	CNT=category
	KEY=nonexisting
	
	KEY="`dialog\
           --title "SETUP :: KEYMAP :: AZERTY" \
           --menu "\nPlease select a map:\n"\
           20 60 12\
	   azerty.map.gz ""\
	   be-latin1.map.gz ""\
	   fr-latin0.map.gz ""\
	   fr-latin1.map.gz ""\
	   fr-pc.map.gz ""\
	   fr.map.gz ""\
	   wangbe.map.gz ""\
	   wangbe2.map.gz ""\
	   2>&1`"

        KEY="/usr/share/keymaps/i386/azerty/${KEY}"
	if [ -f "$KEY" ]
	then
		loadkeys $KEY
		CNT="stop"
	fi
}

Dvorak() {
       
        CNT=category
        KEY=nonexisting
	
	KEY="`dialog\
           --title "SETUP :: KEYMAP :: DVORAK" \
           --menu "\nPlease select a map:\n"\
           20 60 12\
	   ANSI-dvorak.map.gz ""\
	   dvorak-l.map.gz ""\
	   dvorak-r.map.gz ""\
	   dvorak.map.gz ""\
	   2>&1`"
	
        KEY="/usr/share/keymaps/i386/dvorak/${KEY}"
	if [ -f "$KEY" ]
	then
		loadkeys $KEY
		CNT="stop"
	fi
}

Qwerty() {
 
 	CNT=category
        KEY=nonexisting
	
	KEY="`dialog\
           --title "SETUP :: KEYMAP :: QWERTY" \
           --menu "\nPlease select a map:\n"\
           20 60 12\
	   bg.map.gz ""\
	   by.map.gz ""\
	   cf.map.gz ""\
	   cz.map.gz ""\
	   defkeymap.map.gz ""\
	   dk.map.gz ""\
	   es.map.gz ""\
	   et.map.gz ""\
	   fi.map.gz ""\
	   gr.map.gz ""\
	   il.map.gz ""\
	   it.map.gz ""\
	   jp106.map.gz ""\
	   lt.map.gz ""\
	   mk.map.gz ""\
	   nl.map.gz ""\
	   no.map.gz ""\
	   pc110.map.gz ""\
	   pl.map.gz ""\
	   ru.map.gz ""\
	   ua.map.gz ""\
	   uk.map.gz ""\
	   us.map.gz ""\
	   2>&1`"
	
        KEY="/usr/share/keymaps/i386/qwerty/${KEY}"
	if [ -f "$KEY" ]
	then
		loadkeys $KEY
		CNT="stop"
	fi
}

Qwertz() {
       	CNT=category
        KEY=nonexisting
	
	KEY="`dialog\
           --title "SETUP :: KEYMAP :: QWERTZ" \
           --menu "\nPlease select a map:\n"\
           20 60 12\
	   croat.map.gz "" \
	   cz-us-qwertz.map.gz "" \
	   de.map.gz "" \
	   fr_CH.map.gz "" \
	   hu.map.gz "" \
	   sg.map.gz "" \
	   sk-qwertz.map.gz "" \
	   slovene.map.gz "" \
	   2>&1`"
	
        KEY="/usr/share/keymaps/i386/qwertz/${KEY}"
	if [ -f "$KEY" ]
	then
		loadkeys $KEY
		CNT="stop"
	fi
}

keymaps
