#!/bin/bash

set -x

wget -m -nH -nv ftp://ftp.scyld.com/pub/diag/ || exit 1

exit 0

# pull out the version string:
# static char version[] =
# "mii-diag.c:v2.11 3/21/2005 Donald Becker (becker@scyld.com)\n"
#pv=$(grep -A 1 '\<version\>.*=' mii-diag.c)
#pv=${pv#*:v}
#pv=${pv%% *}
#pn="mii-diag"

pn=ethercard-diag
pv=$(date +"%Y%m%d")
p=${pn}-${pv}

rm -rf ../${p} ../${p}.tar.bz2
mkdir ../${p} || exit 1
cp -r * ../${p}/ || exit 1
tar jcf ../${p}.tar.bz2 -C .. ${p} || exit 1
rm -rf ../${p}
du -b ../${p}.tar.bz2
