#!/bin/bash 
usage="Usage: lyx2guide file.sgml file.xml"

if [ -z "${2}" ]; then
    echo $usage
    exit 1
fi

sgml2xml ${1} > ${1}.xml1 2>/dev/null

sed -e 's/&dollar;/$/g' \
    -e 's/&ldquo;/"/g' \
    -e 's/&rdquo;/"/g' \
    -e 's/&lcub;/{/g' \
    -e 's/&rcub;/}/g' \
    -e 's/&lsqb;/[/g' \
    -e 's/&rsqb;/]/g' \
    -e 's/&num;/#/g' \
    ${1}.xml1 > ${1}.xml2

xsltproc /usr/src/gentoo-src/gentoo-web/xsl/lyx-to-gentoo.xslt ${1}.xml2 > ${1}.xml3

sed -e 's/   <\/pre>/<\/pre>/g' ${1}.xml3 > ${2}

xsltproc /usr/src/gentoo-src/gentoo-web/xsl/guide-main.xsl ${2} > ${2//.xml}.html

rm ${1}.xml{1,2,3}

