#!/bin/bash
# Copyright 1999-2004 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo/src/wine/misc/Attic/regedit,v 1.6 2004/10/31 00:55:21 vapier Exp $

source wine-setup || exit 1

export RUNWINE="${INSTALLDIR}/bin/regedit-bin"

exec "${RUNWINE}" "$@"
