#!/bin/bash
# The wine regedit wrapper

export INSTALLDIR="/usr/"

export WINEPREFIX="${WINEPREFIX:-$HOME/.wine}"

export LD_LIBRARY_PATH="$INSTALLDIR/lib/wine:$INSTALLDIR/lib:$LD_LIBRARY_PATH"
export WINEDLLPATH="$LD_LIBRARY_PATH"

export WINE_LOADER=wine

export RUNWINE="${INSTALLDIR}/bin/wine"

export REGEDIT="$INSTALLDIR/bin/regedit-bin"

exec "${REGEDIT}" "$@"
