#!/bin/bash
# Copyright 1999-2004 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo/src/wine/misc/Attic/wine,v 1.5 2004/10/27 15:55:06 vapier Exp $

# The wine wrapper

export INSTALLDIR="/usr/"

export WINEPREFIX="${WINEPREFIX:-$HOME/.wine}"

export LD_LIBRARY_PATH="$INSTALLDIR/lib/wine:$INSTALLDIR/lib:$LD_LIBRARY_PATH"
export WINEDLLPATH="$LD_LIBRARY_PATH"

export RUNWINE="${INSTALLDIR}/bin/wine-bin"

if [ ! -f "$WINEPREFIX/config" ]
then
	echo "!! ~/.wine/config misses"
	echo "!! Setting up a config file"

	mkdir -p ${WINEPREFIX}/fake_windows

	# First copy in the new config file.
	cp "${INSTALLDIR}/share/wine/data/config" "${WINEPREFIX}/config"

	echo "!! Setting up ~/.wine/fake_windows/"
	cp -R ${INSTALLDIR}/share/wine/data/fake_windows/* ${WINEPREFIX}/fake_windows/

	echo "!! Setting up default registry."
	if [ -f "${INSTALLDIR}/share/wine/data/winedefault.reg" ] ; then
		regedit "${INSTALLDIR}/share/wine/data/winedefault.reg" &> /dev/null
	else
		wine rundll32 setupapi.dll,InstallHinfSection DefaultInstall 128 "${INSTALLDIR}/share/wine/data/wine.inf" &> /dev/null
	fi

	echo "!! Installation complete."
	echo "!! Set your drives in ~/.wine/config"
	exit
fi

# Force the use of the more memory-efficient MSVC 5 allocator with
# any programs that use MSVCRT.  This reduces memory consumption
# significantly.
export __MSVCRT_HEAP_SELECT=__GLOBAL_HEAP_SELECTED,2

export PATH="$INSTALLDIR/bin:$PATH"

export WINEDEBUG="${WINEDEBUG:--all}"
exec "$RUNWINE" "$@"
