#!/bin/bash
# Copyright 1999-2004 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo/src/wine/misc/Attic/winedbg,v 1.5 2004/10/27 16:01:20 vapier Exp $

source wine-setup || exit 1

export RUNWINE="${INSTALLDIR}/bin/winedbg-bin"

# Force the use of the more memory-efficient MSVC 5 allocator with
# any programs that use MSVCRT.  This reduces memory consumption
# significantly.
export __MSVCRT_HEAP_SELECT=__GLOBAL_HEAP_SELECTED,2

export WINEDEBUG="${WINEDEBUG:--all}"
exec "$RUNWINE" "$@"
