#!/bin/bash
# The wine wrapper

export INSTALLDIR="/usr/"

export WINEPREFIX="${WINEPREFIX:-$HOME/.wine}"

export LD_LIBRARY_PATH="$INSTALLDIR/lib/wine:$INSTALLDIR/lib:$LD_LIBRARY_PATH"
export WINEDLLPATH="$LD_LIBRARY_PATH"

export RUNWINE="${INSTALLDIR}/bin/wine-bin"

if [ ! -f "$WINEPREFIX/config" ]
then
	echo "!! ~/.wine/config misses"
	echo "!! Setting up a config file"

	mkdir -p ${WINEPREFIX}/fake_windows

	# First copy in the new config file.
	cp "${INSTALLDIR}/share/wine/data/config" "${WINEPREFIX}/config"

	echo "!! Setting up ~/.wine/fake_windows/"
	cp -R ${INSTALLDIR}/share/wine/data/fake_windows ${WINEPREFIX}/fake_windows

	echo "!! Setting up default registry."
	regedit "${INSTALLDIR}/share/wine/data/winedefault.reg" &> /dev/null

	echo "!! Installation complete."
	echo "!! Set your drives in ~/.wine/config"
	exit
fi

# Force the use of the more memory-efficient MSVC 5 allocator with
# any programs that use MSVCRT.  This reduces memory consumption
# significantly.
export __MSVCRT_HEAP_SELECT=__GLOBAL_HEAP_SELECTED,2

export PATH="$INSTALLDIR/bin:$PATH"

export WINEDEBUG="${WINEDEBUG:--all}"
exec "$RUNWINE" "$@"
