#!/bin/bash
# Copyright 1999-2004 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo/src/wine/misc/Attic/wine-setup,v 1.2 2004/10/31 00:51:23 vapier Exp $

# Setup the Gentoo wine environment:
#  - generate $WINEPREFIX with some sane defaults if need be
#  - export a bunch of vars

export INSTALLDIR="/usr/"

export WINEPREFIX="${WINEPREFIX:-$HOME/.wine}"

export LD_LIBRARY_PATH="$INSTALLDIR/lib/wine:$INSTALLDIR/lib:$LD_LIBRARY_PATH"
export WINEDLLPATH="$LD_LIBRARY_PATH"

if [ ! -f "$WINEPREFIX/config" ]
then
	echo "!! ~/.wine/config misses"
	echo "!! Setting up a config file"

	mkdir -p ${WINEPREFIX}/fake_windows

	# First copy in the new config file.
	if ! cp "${INSTALLDIR}/share/wine/data/config" "${WINEPREFIX}/config" ; then
		echo "!! could not find ${INSTALLDIR}/share/wine/data/config"
		exit 1
	fi

	echo "!! Setting up ~/.wine/fake_windows/"
	cp -R ${INSTALLDIR}/share/wine/data/fake_windows/* ${WINEPREFIX}/fake_windows/

	echo "!! Setting up default registry."
	if [ -f "${INSTALLDIR}/share/wine/data/winedefault.reg" ] ; then
		regedit "${INSTALLDIR}/share/wine/data/winedefault.reg" &> /dev/null
	else
		wine rundll32 setupapi.dll,InstallHinfSection DefaultInstall 128 "${INSTALLDIR}/share/wine/data/wine.inf" &> /dev/null
	fi

	echo "!! Installation complete."
	echo "!! Set your drives in ~/.wine/config"
	exit
fi

export PATH="$INSTALLDIR/bin:$PATH"
